@hostname = http://127.0.0.1
@port = 8088
@host = {{hostname}}:{{port}}
@baseUrl = {{host}}
@contentType = application/json


### Get All
GET {{baseUrl}}/songs-data

### Get Songs for paginaltion
GET {{baseUrl}}/songs-data?_page=90

### Get Songs by search
GET {{baseUrl}}/songs-data?_serch=dosti

### Get Songs by redis search
GET {{baseUrl}}/search-song?_serch=dosti

### Get Individual song
GET {{baseUrl}}/songs-data?_id=830fb77c-cef6-43f8-bd59-507155b0bcac

### Get song url
GET {{baseUrl}}/play-song?_id=e02833d0-e5d1-4bc7-90ab-fa9ac7ba8d9d