version: '3.8'

# networks:
#     aTunes:
#         external: true

volumes:
    psql_data: {}
    psql_data_backup: {}
    redis_data: {}

services:
    api:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.local
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        image: 'atune_image_local'
        command: ['sh', '-c', 'python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --reload --host 0.0.0.0 --port 8000']
        ports:
            - 8088:8000
            - 5678:5678
        volumes:
            - ./src:/app
        # networks:
        #     - aTunes
        env_file:
            - ./.envs/_api.env
            - ./.envs/_db.env
        depends_on:
            - db

    db:
        image: ${DB_IMAGE}
        # networks:
        #     - aTunes
        env_file:
            - ./.envs/_db.env
        volumes:
            - psql_data:/var/lib/postgresql/data:Z
            - psql_data_backup:/backups:z

    redis:
        image: ${REDIS_IMAGE}
        # networks:
        #     - aTunes
        env_file:
            - ./.envs/_redis.env
        depends_on:
            - db
        volumes:
            - redis_data:/data
