version: '3.8'

# networks:
#     aTunes:
#         external: true

services:
    api:
        build: src
        command: uvicorn main:app --host 0.0.0.0 --reload
        ports:
            - 8088:8000
        volumes:
            - ./src:/app
        # networks:
        #     - aTunes
        env_file:
            - ./.envs/_api.env
            - ./.envs/_db.env
        depends_on:
            - db

    db:
        image: postgres
        # networks:
        #     - aTunes
        env_file:
            - ./.envs/_db.env

    redis:
        image: 'redis:alpine'
        # networks:
        #     - aTunes
        env_file:
            - ./.envs/_redis.env
        depends_on:
            - db
