version: '3.8'

volumes:
    psql_data: {}
    psql_data_backup: {}
    redis_data: {}

services:
    server:
        image: nginx:alpine
        container_name: server
        restart: always
        volumes:
            - ./.server/nginx/conf/:/etc/nginx/conf.d/:ro
            - ./.server/certbot/www:/var/www/certbot/:ro
            - ./.server/certbot/conf/:/etc/nginx/ssl/:ro
        ports:
            - 80:80
            - 443:443
        links:
            - api

    api:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.production
            args:
                - PYTHON_VERSION=tiangolo/uvicorn-gunicorn-fastapi:python3.8
        image: atunes_backend:latest
        container_name: atb
        command: uvicorn main:app --host 0.0.0.0 --reload
        env_file:
            - ./.envs/_api.env
            - ./.envs/_db.env
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: db
        env_file:
            - ./.envs/_db.env
        volumes:
            - psql_data:/var/lib/postgresql/data

    search:
        image: redislabs/redisearch:latest
        container_name: caching
        depends_on:
            - db
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        volumes:
            - redis_data:/data

    certbot:
        image: certbot/certbot:latest
        container_name: bot
        volumes:
            - ./.server/certbot/www/:/var/www/certbot/:rw
            - ./.server/certbot/conf/:/etc/letsencrypt/:rw
