version: '3.8'

volumes:
    psql_data: {}
    psql_data_backup: {}
    redis_data: {}

services:
    web:
        build:
            context: .
            dockerfile: ./.nginx/Dockerfile
        ports:
            - 8080:80
            - 443:443
        depends_on:
            - api

    api:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.production
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        image: atune_image_production:latest
        command: uvicorn main:app --host 0.0.0.0 --reload
        ports:
            - 8080:8000
        env_file:
            - ./.envs/_api.env
            - ./.envs/_db.env
        depends_on:
            - db

    db:
        image: ${DB_IMAGE}
        env_file:
            - ./.envs/_db.env
        volumes:
            - psql_data:/var/lib/postgresql/data:Z
            - psql_data_backup:/backups:z

    redis:
        image: ${REDIS_IMAGE}
        env_file:
            - ./.envs/_redis.env
        depends_on:
            - db
        volumes:
            - redis_data:/data
