version: '3.8'

volumes:
    psql_data: {}
    psql_data_backup: {}
    redis_data: {}

services:
    web:
        image: nginx:alpine
        container_name: proxy-app
        # build:
        #   context: .
        #   dockerfile: ./.nginx/Dockerfile
        volumes:
            - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
            - 443:443
        depends_on:
            - api

    api:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.production
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        image: atune_backend:latest
        container_name: atune_backend
        command: uvicorn main:app --host 0.0.0.0 --reload
        env_file:
            - ./.envs/_api.env
            - ./.envs/_db.env
        depends_on:
            - db

    db:
        image: ${DB_IMAGE}
        container_name: database
        env_file:
            - ./.envs/_db.env
        volumes:
            - psql_data:/var/lib/postgresql/data:Z
            - psql_data_backup:/backups:z

    redis:
        image: ${REDIS_IMAGE}
        container_name: caching-db
        env_file:
            - ./.envs/_redis.env
        depends_on:
            - db
        volumes:
            - redis_data:/data
