version: '3.8'

volumes:
    psql_data: {}
    psql_data_backup: {}
    redis_data: {}

services:
    server:
        image: nginx:alpine
        container_name: server
        restart: always
        # build:
        #   context: .
        #   dockerfile: ./.nginx/Dockerfile
        volumes:
            - ./.nginx/conf/:/etc/nginx/conf.d/:ro
            - ./.nginx/certbot/www:/var/www/certbot/:ro
            - ./.nginx/certbot/conf/:/etc/nginx/ssl/:ro
        ports:
            - 80:80
            - 443:443
        # depends_on:
        #     - api
        links:
            - api

    api:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.production
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        image: atunes_backend:latest
        container_name: atb
        command: uvicorn main:app --host 0.0.0.0 --reload
        env_file:
            - ./.envs/_api.env
            - ./.envs/_db.env
        depends_on:
            - db

    db:
        image: ${DB_IMAGE}
        container_name: db
        env_file:
            - ./.envs/_db.env
        volumes:
            - psql_data:/var/lib/postgresql/data:Z
            - psql_data_backup:/backups:z

    redis:
        image: ${REDIS_IMAGE}
        container_name: redis
        env_file:
            - ./.envs/_redis.env
        depends_on:
            - db
        volumes:
            - redis_data:/data

    certbot:
        image: certbot/certbot:latest
        container_name: bot
        volumes:
            - ./.nginx/certbot/www/:/var/www/certbot/:rw
            - ./.nginx/certbot/conf/:/etc/letsencrypt/:rw
